# Generated by Django 5.1.2 on 2024-10-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='wardrobe_images/')),
            ],
        ),
    ]
